import sgMail from '@sendgrid/mail';
import { log } from './logger.js';

if (process.env.SENDGRID_API_KEY) {
    sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export interface DigestEmailData {
    to: string;
    orgName: string;
    overallScore: number;
    driftAlerts: string[];
    topActions: string[];
    reportLink: string;
}

export async function sendStrategyDigest(data: DigestEmailData): Promise<boolean> {
    if (!process.env.SENDGRID_API_KEY) {
        log({ severity: 'WARNING', message: 'SENDGRID_API_KEY not set. Skipping email.', org: data.orgName });
        return false;
    }

    const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h2 style="color: #6d28d9;">VelocityCSO Weekly Digest</h2>
        <p>Here is the latest strategic pulse for <strong>${data.orgName}</strong>.</p>
        
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3>Current Strategic Density: ${data.overallScore}/100</h3>
        </div>

        ${data.driftAlerts.length > 0 ? `
        <div style="border-left: 4px solid #f59e0b; padding-left: 15px; margin: 20px 0;">
            <h4 style="color: #d97706; margin-top: 0;">⚠ Dimension Drift Alerts</h4>
            <ul>
                ${data.driftAlerts.map(alert => `<li>${alert}</li>`).join('')}
            </ul>
        </div>
        ` : ''}

        ${data.topActions.length > 0 ? `
        <div style="border-left: 4px solid #10b981; padding-left: 15px; margin: 20px 0;">
            <h4 style="color: #059669; margin-top: 0;">Top Priority Actions</h4>
            <ul>
                ${data.topActions.map(action => `<li>${action}</li>`).join('')}
            </ul>
        </div>
        ` : ''}

        <div style="margin-top: 30px;">
            <a href="${data.reportLink}" style="background: #6d28d9; color: white; text-decoration: none; padding: 10px 20px; border-radius: 5px; display: inline-block;">
                View Full Audit History
            </a>
        </div>
        
        <p style="margin-top: 40px; font-size: 12px; color: #94a3b8;">
            Generated by VelocityCSO<br/>
            Strategy at the Speed of Thought.
        </p>
    </div>
    `.trim();

    try {
        await sgMail.send({
            to: data.to,
            from: 'digests@velocitycso.com', // Must be verified in SendGrid
            subject: `[VelocityCSO] Strategic Pulse: ${data.orgName}`,
            html: htmlContent,
        });

        log({
            severity: 'INFO',
            message: 'Digest email sent',
            org: data.orgName,
            recipient: data.to
        });
        return true;
    } catch (error: any) {
        log({
            severity: 'ERROR',
            message: 'Failed to send digest email',
            org: data.orgName,
            error: error.message
        });
        return false;
    }
}
