import PDFDocument from 'pdfkit';
import type { AuditMemory } from './memory.js';
import { renderCharts, type ChartImages } from './chartService.js';
import { log } from './logger.js';

// ─── Design Tokens ────────────────────────────────────────────────────────────
const NAVY = '#0D1B2A';
const BLUE = '#1B4F8A';
const ACCENT = '#2563EB';
const GRAY = '#6B7280';
const WHITE = '#FFFFFF';
const RED = '#DC2626';
const GREEN = '#16A34A';
const ORANGE = '#EA580C';
const FOOTER = 'Generated by VelocityCSO.com — Powered by Gemini';

const CATEGORIES: Record<string, string[]> = {
    'Market': ['TAM Viability', 'Target Precision', 'Trend Adoption', 'Team / Founder Strength'],
    'Strategy': ['Competitive Defensibility', 'Model Innovation', 'Flywheel Potential', 'Network Effects Strength', 'Data Asset Quality'],
    'Commercial': ['Pricing Power', 'CAC/LTV Ratio', 'Market Entry Speed'],
    'Operations': ['Execution Speed', 'Scalability', 'ESG Posture', 'Regulatory Readiness'],
    'Finance': ['ROI Projection', 'Risk Tolerance', 'Capital Efficiency', 'Customer Concentration Risk'],
};

const SCENARIO_LABELS: Record<string, string> = {
    RECESSION: 'Economic Recession',
    PRICE_WAR: 'Competitor Price War',
    SCALE_UP: 'Aggressive Scale-Up',
    TALENT: 'Global Talent Shortage',
    REGULATORY: 'Aggressive Regulatory Crackdown',
};

// Inline stress prompts — avoids importing scenarios.ts circular dep
const SCENARIO_PROMPTS: Record<string, string> = {
    RECESSION: 'Global GDP contracts 3%. Consumer spending drops 15%. Credit tightens. Enterprise budgets cut 20-30%.',
    PRICE_WAR: 'A well-funded competitor cuts prices 40%. Customers demand price matching. Margins compress 25%.',
    SCALE_UP: 'Board demands 3x growth in 18 months. Headcount must triple. Infrastructure costs spike 200%.',
    TALENT: 'Senior engineering talent costs double. Key hires take 6+ months. Attrition hits 30% annually.',
    REGULATORY: 'Major regulatory framework changes over 18 months limit data usage and increase compliance costs by 40%.',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
function sanitizeText(text: string): string {
    if (!text) return '';
    // Strip emojis and non-printable ASCII characters that break standard PDF encoding
    // Allow basic ASCII, newlines, tabs, and common typography (quotes, dashes)
    return text.replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF\u2013-\u201D\u2018-\u2019]/g, '').trim();
}
function drawHeader(doc: PDFKit.PDFDocument, title: string) {
    const safeTitle = sanitizeText(title).toUpperCase();
    doc.rect(0, 0, doc.page.width, 48).fill(NAVY);
    doc.fontSize(7).fillColor(WHITE).font('Helvetica')
        .text('CONFIDENTIAL STRATEGY AUDIT', 40, 18, { align: 'left' });
    doc.fontSize(7).fillColor(WHITE)
        .text(safeTitle, 0, 18, { align: 'right', width: doc.page.width - 40 });
}

function drawFooter(doc: PDFKit.PDFDocument, page: number) {
    const y = doc.page.height - 32;
    doc.rect(0, y, doc.page.width, 32).fill(NAVY);
    doc.fontSize(7).fillColor(WHITE).font('Helvetica')
        .text(FOOTER, 40, y + 10, { align: 'left' });
    doc.text(`Page ${page}`, 0, y + 10, { align: 'right', width: doc.page.width - 40 });
}

function sectionTitle(doc: PDFKit.PDFDocument, text: string, y: number) {
    doc.rect(40, y, 4, 16).fill(ACCENT);
    doc.fontSize(10).fillColor(NAVY).font('Helvetica-Bold').text(text, 52, y + 1);
    return y + 26;
}

function scoreBar(doc: PDFKit.PDFDocument, label: string, score: number, baseline: number | undefined, y: number, colX = 40, colW = 480) {
    const barX = colX + 150;
    const barW = colW - 170;
    const filled = Math.round((score / 100) * barW);
    const color = score >= 70 ? GREEN : score >= 40 ? BLUE : RED;
    const dropped = baseline !== undefined && (baseline - score) > 10;
    doc.fontSize(7.5).fillColor(dropped ? ORANGE : NAVY).font(dropped ? 'Helvetica-Bold' : 'Helvetica')
        .text((dropped ? '▼ ' : '') + label, colX, y, { width: 148 });
    doc.rect(barX, y + 2, barW, 7).fill('#E5E7EB');
    doc.rect(barX, y + 2, filled, 7).fill(color);
    if (baseline !== undefined && dropped) {
        const baselineFilled = Math.round((baseline / 100) * barW);
        doc.rect(barX + filled, y + 2, baselineFilled - filled, 7).fillOpacity(0.3).fill(GRAY).fillOpacity(1);
    }
    doc.fontSize(7.5).fillColor(color).font('Helvetica-Bold').text(`${score}`, barX + barW + 4, y);
    if (baseline !== undefined && dropped) {
        doc.fontSize(6.5).fillColor(RED).font('Helvetica').text(`↓${baseline - score}`, barX + barW + 22, y + 1);
    }
    return y + 15;
}

function addPage(doc: PDFKit.PDFDocument, orgName: string) {
    doc.addPage();
    drawHeader(doc, orgName);
    return 60;
}

function extractOrgName(context: string): string {
    const match = context.match(/^([A-Z][a-zA-Z\s&]{2,40})/);
    return match ? match[1].trim() : 'Your Organisation';
}

function extractKillerMove(report: string): string {
    const match = report.match(/\*\*([^*]{10,120})\*\*/);
    if (match) return match[1].trim().slice(0, 120);
    const lines = report.split('\n').filter(l => l.trim().length > 20);
    return lines[0]?.replace(/[#*]/g, '').trim().slice(0, 120) || 'Strategic audit complete.';
}

// Run a single stress scenario via Gemini directly (no ADK runner needed)
async function runStressScenario(
    scenarioId: string,
    businessContext: string,
    dimensionScores: Record<string, number | null>
): Promise<{ stressedScores: Record<string, number>; mitigationCards: any[] }> {
    try {
        const { LlmAgent, InMemoryRunner, isFinalResponse } = await import('@google/adk');
        const { randomUUID } = await import('crypto');

        const dimNames = Object.keys(CATEGORIES).flatMap(k => CATEGORIES[k]);
        const prompt = `
You are a stress-test analyst. Given this business context and baseline scores, recalculate all 20 dimensions under the crisis scenario.

BUSINESS: ${businessContext.slice(0, 500)}

BASELINE SCORES: ${JSON.stringify(dimensionScores)}

CRISIS: ${SCENARIO_PROMPTS[scenarioId]}

Return ONLY raw JSON:
{
  "stressed_scores": { "TAM Viability": 60, ... all 20 ... },
  "mitigation_cards": [
    { "dimension": "...", "stressed_score": 30, "risk_delta": 20, "mitigation_steps": ["...","...","..."], "cso_crisis_play": "..." }
  ]
}
Only include dimensions with stressed_score < 40 in mitigation_cards.
Dimensions: ${dimNames.join(', ')}`.trim();

        const agent = new LlmAgent({
            name: 'pdf_stress_agent',
            model: 'gemini-2.5-flash',
            description: 'Stress test for PDF',
            instruction: 'Return only raw JSON as instructed.',
        });
        const runner = new InMemoryRunner({ agent, appName: 'pdf_stress' });
        const sid = randomUUID();
        await runner.sessionService.createSession({ appName: 'pdf_stress', userId: 'pdf_user', sessionId: sid });
        const stream = runner.runAsync({ userId: 'pdf_user', sessionId: sid, newMessage: { role: 'user', parts: [{ text: prompt }] } });
        let raw = '';
        for await (const ev of stream) {
            if (ev.author === agent.name || isFinalResponse(ev)) {
                const text = (ev.content?.parts || []).map((p: any) => p.text).filter(Boolean).join('');
                if (text) raw += text;
            }
        }
        const m = raw.match(/\{[\s\S]*\}/);
        if (m) {
            const p = JSON.parse(m[0]);
            return { stressedScores: p.stressed_scores || {}, mitigationCards: p.mitigation_cards || [] };
        }
    } catch { /* fallback below */ }

    // Fallback: apply fixed deltas
    const stressedScores: Record<string, number> = {};
    const deltas: Record<string, number> = { RECESSION: -18, PRICE_WAR: -15, SCALE_UP: -12, TALENT: -10, REGULATORY: -22 };
    const delta = deltas[scenarioId] || -12;
    for (const [dim, score] of Object.entries(dimensionScores)) {
        stressedScores[dim] = Math.max(0, (score ?? 0) + delta);
    }
    return { stressedScores, mitigationCards: [] };
}

// ─── Main export ──────────────────────────────────────────────────────────────
export async function generatePDF(memory: AuditMemory, reportId = ''): Promise<Buffer> {
    const sessionId = memory.reportId || reportId || 'pdf_gen';

    // Run stress scenarios + chart rendering in parallel
    const scenarioIds = ['RECESSION', 'PRICE_WAR', 'SCALE_UP', 'TALENT', 'REGULATORY'];
    const [stressResults, chartImages] = await Promise.all([
        Promise.all(scenarioIds.map(id => runStressScenario(id, memory.businessContext, memory.dimensionScores))),
        renderCharts(memory, sessionId, reportId).catch((err: unknown) => {
            log({ severity: 'WARNING', message: 'generatePDF | charts_skipped', error: String(err), session_id: sessionId });
            return {} as ChartImages;
        }),
    ]);

    const stressMap: Record<string, { stressedScores: Record<string, number>; mitigationCards: any[] }> = {};
    scenarioIds.forEach((id, i) => { stressMap[id] = stressResults[i]; });

    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        const doc = new PDFDocument({ size: 'A4', margin: 0, bufferPages: true });
        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        _buildPDF(doc, memory, stressMap, chartImages);
    });
}

// ─── Chart helpers ─────────────────────────────────────────────────────────────
function embedChart(doc: PDFKit.PDFDocument, b64: string, x: number, y: number, w: number, h: number): boolean {
    if (!b64) return false;
    try {
        const buf = Buffer.from(b64, 'base64');
        doc.image(buf, x, y, { width: w, height: h });
        return true;
    } catch {
        return false;
    }
}

function chartFallbackText(doc: PDFKit.PDFDocument, message: string, x: number, y: number, w: number) {
    doc.rect(x, y, w, 28).fill('#F3F4F6');
    doc.fontSize(7.5).fillColor(GRAY).font('Helvetica-Oblique')
        .text(message, x + 8, y + 8, { width: w - 16 });
}

function _buildPDF(
    doc: PDFKit.PDFDocument,
    memory: AuditMemory,
    stressMap: Record<string, { stressedScores: Record<string, number>; mitigationCards: any[] }>,
    charts: ChartImages = {}
): void {
    const orgName = sanitizeText(memory.orgName || extractOrgName(memory.businessContext || ''));
    const killerMove = extractKillerMove(memory.report);
    const dims = memory.dimensionScores;
    const scoredValues = Object.values(dims).filter((v): v is number => v !== null);
    const overallScore = scoredValues.length
        ? Math.round(scoredValues.reduce((a, b) => a + b, 0) / scoredValues.length)
        : 0;
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    let page = 1;

    // ── PAGE 1: Cover ─────────────────────────────────────────────────────────
    drawHeader(doc, orgName);
    doc.rect(0, 48, doc.page.width, 220).fill(NAVY);

    // Decorative element
    doc.rect(40, 72, 2, 80).fill(ACCENT);

    doc.fontSize(28).fillColor(WHITE).font('Helvetica-Bold').text('Executive Strategy Audit', 55, 72);
    doc.fontSize(16).fillColor('#93C5FD').font('Helvetica').text(orgName, 55, 106);
    doc.fontSize(10).fillColor('#94A3B8').text(`${date}  ·  Strategic Density: ${overallScore}/100`, 55, 132);

    let y = 290;
    y = sectionTitle(doc, 'Executive Verdict', y);
    doc.fontSize(13).fillColor(NAVY).font('Helvetica-Bold')
        .text(`"${killerMove}"`, 40, y, { width: doc.page.width - 80 });
    y = doc.y + 25;

    const moatLabel = overallScore >= 70 ? 'STRONG MOAT' : overallScore >= 40 ? 'DEVELOPING MOAT' : 'FRAGILE MOAT';
    const moatColor = overallScore >= 70 ? GREEN : overallScore >= 40 ? BLUE : RED;

    // Pill design for status
    doc.rect(40, y, 140, 24).fill(moatColor);
    doc.fontSize(9).fillColor(WHITE).font('Helvetica-Bold').text(moatLabel, 40, y + 7, { width: 140, align: 'center' });

    doc.fontSize(9).fillColor(NAVY).font('Helvetica').text(`Confidence Index: ${overallScore}%`, 194, y + 8);
    y += 45;

    if (memory.moatRationale) {
        doc.fontSize(8).fillColor(GRAY).font('Helvetica-Oblique')
            .text(sanitizeText(memory.moatRationale), 40, y, { width: doc.page.width - 80, lineGap: 2 });
    }

    drawFooter(doc, page++);

    // ── PAGE 2: Table of Contents ─────────────────────────────────────────────
    y = addPage(doc, orgName);
    y = sectionTitle(doc, 'Table of Contents', y);

    const tocItems = [
        '1. Executive Summary',
        '2. Strategic Diagnostic Matrix (20 Dimensions)',
        '3. Detailed Tactical Audit',
        '4. Strategic Recommendations (90-Day Roadmap)',
        '5. Adversarial Stress Scenarios',
        '6. Sources Appendix'
    ];

    let tocY = y + 10;
    for (const item of tocItems) {
        doc.fontSize(10).fillColor(BLUE).font('Helvetica-Bold').text(item, 40, tocY);
        doc.moveTo(40, tocY + 14).lineTo(doc.page.width - 40, tocY + 14).lineWidth(0.5).strokeOpacity(0.2).stroke(GRAY).strokeOpacity(1);
        tocY += 24;
    }

    drawFooter(doc, page++);

    // ── PAGE 3: 20-Dimension Heatmap & Radar Chart ───────────────────────────
    y = addPage(doc, orgName);
    y = sectionTitle(doc, 'Strategic Diagnostic Matrix (20 Dimensions)', y);

    const midPoint = doc.page.width / 2;
    let leftHalfY = y;
    let rightHalfY = y;

    const catEntries = Object.entries(CATEGORIES);
    const splitIndex = 3; // Market, Strategy, Commercial on left; Operations, Finance on right

    // Draw Radar Chart
    const radarCx = midPoint;
    const radarCy = doc.page.height - 230;
    const radarRadius = 80;
    const dimNames = Object.keys(CATEGORIES).flatMap(k => CATEGORIES[k]);
    const angleStep = (Math.PI * 2) / dimNames.length;

    // Draw radar web
    doc.lineWidth(0.5).strokeColor('#E5E7EB');
    for (let r = 0.2; r <= 1; r += 0.2) {
        doc.polygon(...dimNames.map((_, i) => [
            radarCx + Math.cos(i * angleStep - Math.PI / 2) * radarRadius * r,
            radarCy + Math.sin(i * angleStep - Math.PI / 2) * radarRadius * r
        ] as [number, number]));
        doc.stroke();
    }
    // Draw radar axes
    dimNames.forEach((_, i) => {
        const x = radarCx + Math.cos(i * angleStep - Math.PI / 2) * radarRadius;
        const y = radarCy + Math.sin(i * angleStep - Math.PI / 2) * radarRadius;
        doc.moveTo(radarCx, radarCy).lineTo(x, y).stroke();
    });
    // Draw data polygon
    const dataPoints = dimNames.map((dim, i) => {
        const score = dims[dim] || 0;
        return [
            radarCx + Math.cos(i * angleStep - Math.PI / 2) * radarRadius * (score / 100),
            radarCy + Math.sin(i * angleStep - Math.PI / 2) * radarRadius * (score / 100)
        ] as [number, number];
    });
    doc.polygon(...dataPoints);
    doc.fillOpacity(0.2).fillAndStroke(ACCENT, ACCENT).fillOpacity(1);

    // Left Column
    for (let i = 0; i < splitIndex; i++) {
        const [cat, dimList] = catEntries[i];
        doc.fontSize(8).fillColor(ACCENT).font('Helvetica-Bold').text(cat.toUpperCase(), 40, leftHalfY);
        leftHalfY += 14;
        for (const dim of dimList) {
            leftHalfY = scoreBar(doc, dim, dims[dim] ?? 0, dims[dim] === null ? undefined : (dims[dim] ?? 0), leftHalfY, 40, midPoint - 60);
        }
        leftHalfY += 10;
    }

    // Right Column
    for (let i = splitIndex; i < catEntries.length; i++) {
        const [cat, dimList] = catEntries[i];
        doc.fontSize(8).fillColor(ACCENT).font('Helvetica-Bold').text(cat.toUpperCase(), midPoint + 10, rightHalfY);
        rightHalfY += 14;
        for (const dim of dimList) {
            rightHalfY = scoreBar(doc, dim, dims[dim] ?? 0, dims[dim] === null ? undefined : (dims[dim] ?? 0), rightHalfY, midPoint + 10, midPoint - 50);
        }
        rightHalfY += 10;
    }

    y = Math.max(leftHalfY, rightHalfY) + 20;

    drawFooter(doc, page++);

    // ── PAGES 4+: Full Strategy Report ────────────────────────────────────────
    y = addPage(doc, orgName);
    y = sectionTitle(doc, 'Detailed Tactical Audit', y);

    const cleanReport = memory.report
        .replace(/```[a-z]*/gi, '').replace(/```/g, '')
        .replace(/\r\n/g, '\n');

    const lines = cleanReport.split('\n');
    const pageBottom = doc.page.height - 44;

    for (const line of lines) {
        if (y > pageBottom) {
            drawFooter(doc, page++);
            y = addPage(doc, orgName);
        }
        const trimmed = line.trim();
        if (!trimmed) { y += 5; continue; }

        if (/^#{1,2}\s/.test(trimmed)) {
            if (y > pageBottom - 30) { drawFooter(doc, page++); y = addPage(doc, orgName); }
            const text = trimmed.replace(/^#+\s*/, '');
            y += 8;
            doc.rect(40, y, 4, 14).fill(ACCENT);
            doc.fontSize(10).fillColor(NAVY).font('Helvetica-Bold').text(text, 52, y + 1, { width: doc.page.width - 92 });
            y = doc.y + 8;
        } else if (/^#{3,}\s/.test(trimmed)) {
            const text = trimmed.replace(/^#+\s*/, '');
            doc.fontSize(9).fillColor(BLUE).font('Helvetica-Bold').text(text, 40, y, { width: doc.page.width - 80 });
            y = doc.y + 6;
        } else if (/^[-*]\s/.test(trimmed)) {
            const text = trimmed.replace(/^[-*]\s*/, '').replace(/\*\*/g, '');
            doc.fontSize(8).fillColor(NAVY).font('Helvetica').text(`• ${text}`, 52, y, { width: doc.page.width - 92 });
            y = doc.y + 4;
        } else {
            const text = trimmed.replace(/\*\*/g, '').replace(/\*/g, '');
            doc.fontSize(8).fillColor('#374151').font('Helvetica').text(text, 40, y, { width: doc.page.width - 80, lineGap: 1.5 });
            y = doc.y + 4;
        }
    }
    drawFooter(doc, page++);

    // ── STRATEGY RECOMMENDATIONS (90-Day Actions) ─────────────────────────────
    const criticalActions = Object.entries(memory.richDimensions || {})
        .filter(([_, data]) => (data.score ?? 0) < 65 && data.improvement_action)
        .map(([dim, data]) => ({ dim, action: data.improvement_action, score: data.score ?? 0, justification: data.justification }));

    if (criticalActions.length > 0) {
        y = addPage(doc, orgName);
        y = sectionTitle(doc, 'Strategic Recommendations (90-Day Roadmap)', y);
        doc.fontSize(8).fillColor(GRAY).font('Helvetica')
            .text('The following high-priority tasks have been identified to address structural gaps in the business model.', 40, y);
        y += 20;

        for (const item of criticalActions) {
            if (y > pageBottom - 60) { drawFooter(doc, page++); y = addPage(doc, orgName); }

            doc.rect(40, y, doc.page.width - 80, 20).fill('#F8FAFC');
            doc.fontSize(9).fillColor(NAVY).font('Helvetica-Bold').text(item.dim, 48, y + 6);
            doc.fontSize(9).fillColor(BLUE).text(`${item.score}/100`, 0, y + 6, { align: 'right', width: doc.page.width - 48 });
            y += 25;

            doc.fontSize(8).fillColor(NAVY).font('Helvetica-Bold').text('DIRECTIVE: ', 40, y, { continued: true })
                .font('Helvetica').text(sanitizeText(item.action), { width: doc.page.width - 80 });
            y = doc.y + 6;

            if (item.justification) {
                doc.fontSize(7.5).fillColor(GRAY).font('Helvetica-Oblique').text(`Rationale: ${sanitizeText(item.justification)}`, 40, y, { width: doc.page.width - 80 });
                y = doc.y + 12;
            }
            y += 4;
        }
        drawFooter(doc, page++);
    }

    // ── STRESS TEST PAGES ──────────────────────────────────────────────────────
    for (const scenarioId of ['RECESSION', 'PRICE_WAR', 'SCALE_UP', 'TALENT', 'REGULATORY']) {
        const result = stressMap[scenarioId];
        if (!result) continue;

        y = addPage(doc, orgName);
        y = sectionTitle(doc, `Stress Test: ${SCENARIO_LABELS[scenarioId]}`, y);

        doc.fontSize(8).fillColor(GRAY).font('Helvetica')
            .text(SCENARIO_PROMPTS[scenarioId], 40, y, { width: doc.page.width - 80 });
        y = doc.y + 16;

        const stressedAvg = Object.values(result.stressedScores).length
            ? Math.round(Object.values(result.stressedScores).reduce((a, b) => a + b, 0) / Object.values(result.stressedScores).length)
            : overallScore;

        const leftHalfY_stress = y;
        const rightHalfY_stress = y;

        // Comparison view
        doc.fontSize(8).fillColor(ACCENT).font('Helvetica-Bold').text('SCENARIO PERFORMANCE', 40, y);
        y += 18;

        let curY = y;
        const allDims = Object.keys(CATEGORIES).flatMap(k => CATEGORIES[k]);
        const half = Math.ceil(allDims.length / 2);

        for (let i = 0; i < allDims.length; i++) {
            if (curY > pageBottom - 20) { drawFooter(doc, page++); curY = addPage(doc, orgName); }
            const dim = allDims[i];
            curY = scoreBar(doc, dim, result.stressedScores[dim] ?? 0, dims[dim] ?? undefined, curY);
        }
        y = curY + 20;

        doc.rect(40, y, doc.page.width - 80, 24).fill('#FEF2F2');
        doc.fontSize(9).fillColor(RED).font('Helvetica-Bold')
            .text(`Impact Assessment: Score reduced to ${stressedAvg}/100  (Delta: ${stressedAvg - overallScore} pts)`, 44, y + 7);
        y += 35;

        // Crisis Mode Banner
        doc.rect(0, y - 24, doc.page.width, 32).fill('#450a0a');
        doc.fontSize(10).fillColor('#FEE2E2').font('Helvetica-Bold')
            .text('⚠ CRITICAL SYSTEM STRESS DETECTED', 0, y - 13, { align: 'center', characterSpacing: 1.5 });
        y += 24;

        if (result.mitigationCards.length > 0) {
            doc.fontSize(12).fillColor(NAVY).font('Helvetica-Bold').text('CRISIS MITIGATION PLAYBOOK', 40, y);
            y += 20;

            for (const card of result.mitigationCards) {
                if (y > pageBottom - 100) { drawFooter(doc, page++); y = addPage(doc, orgName); }

                // Dim Header with score
                doc.rect(40, y, doc.page.width - 80, 22).fill('#fef2f2');
                doc.rect(40, y, 3, 22).fill(RED);
                doc.fontSize(9).fillColor(RED).font('Helvetica-Bold')
                    .text(`${card.dimension.toUpperCase()}`, 48, y + 7, { continued: true })
                    .font('Helvetica').fillColor('#7f1d1d')
                    .text(`  |  Resilience: ${card.stressed_score ?? card.stressedScore}/100`);
                y += 30;

                // Steps
                for (const step of (card.mitigation_steps || card.mitigationSteps || [])) {
                    if (y > pageBottom - 24) { drawFooter(doc, page++); y = addPage(doc, orgName); }
                    doc.circle(46, y + 4, 1.5).fill(RED);
                    doc.fontSize(8).fillColor(NAVY).font('Helvetica').text(step, 54, y, { width: doc.page.width - 104 });
                    y = doc.y + 6;
                }

                if (card.cso_crisis_play || card.csoCrisisPlay) {
                    y += 6;
                    if (y > pageBottom - 50) { drawFooter(doc, page++); y = addPage(doc, orgName); }

                    // CSO Commander Directive Box
                    const directive = (card.cso_crisis_play || card.csoCrisisPlay);
                    const directiveHeight = doc.fontSize(8).heightOfString(directive, { width: doc.page.width - 110 }) + 20;

                    doc.roundedRect(48, y, doc.page.width - 96, directiveHeight, 4).fill('#EFF6FF');
                    doc.fontSize(7).fillColor(BLUE).font('Helvetica-Bold')
                        .text('COMMANDER DIRECTIVE', 56, y + 6);
                    doc.fontSize(8).fillColor('#1e3a8a').font('Helvetica-Oblique')
                        .text(`"${directive}"`, 56, y + 16, { width: doc.page.width - 112 });
                    y += directiveHeight + 15;
                }
                y += 5;
            }
        }
        drawFooter(doc, page++);
    }

    // ── STRATEGIC FRAMEWORKS ───────────────────────────────────────────────────
    const fw = memory.frameworks ?? {};
    const hasFrameworks = Object.keys(fw).some(k => fw[k]);
    if (hasFrameworks) {
        const pageW = doc.page.width;
        const chartW = pageW - 80;
        const chartH = 320;

        // Porter's Five Forces
        if (fw.porter) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, "Porter's Five Forces Analysis", y);
            if (!embedChart(doc, charts.porter ?? '', 40, y, chartW, chartH)) {
                const scores = fw.porter?.scores ?? {};
                for (const [force, entry] of Object.entries(scores) as [string, any][]) {
                    const label = force.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
                    y = scoreBar(doc, label, entry?.score ?? 50, undefined, y);
                }
            } else { y += chartH + 8; }
            if (fw.porter?.interaction_effect_warning) {
                doc.fontSize(7.5).fillColor(ORANGE).font('Helvetica-Oblique')
                    .text(`Note: ${sanitizeText(fw.porter.interaction_effect_warning)}`, 40, y, { width: chartW });
                y = doc.y + 6;
            }
            drawFooter(doc, page++);
        }

        // Ansoff Matrix
        if (fw.ansoff) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'Ansoff Growth Matrix', y);
            if (!embedChart(doc, charts.ansoff ?? '', 40, y, chartW, chartH)) {
                chartFallbackText(doc, 'Ansoff matrix chart unavailable — see data below.', 40, y, chartW);
                y += 36;
                for (const key of ['market_penetration','market_development','product_development','diversification']) {
                    const q = fw.ansoff?.[key];
                    if (!q) continue;
                    const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
                    y = scoreBar(doc, label, q.score ?? 50, undefined, y);
                    if (q.killer_move) {
                        doc.fontSize(7).fillColor(GRAY).font('Helvetica-Oblique')
                            .text(`  → ${sanitizeText(q.killer_move)}`, 40, y, { width: chartW });
                        y = doc.y + 4;
                    }
                }
            } else { y += chartH + 8; }
            if (fw.ansoff?.strategic_verdict) {
                doc.fontSize(7.5).fillColor(NAVY).font('Helvetica')
                    .text(sanitizeText(fw.ansoff.strategic_verdict), 40, y, { width: chartW });
                y = doc.y + 10;
            }
            drawFooter(doc, page++);
        }

        // VRIO
        if (fw.vrio) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'VRIO Resource Analysis', y);
            if (!embedChart(doc, charts.vrio ?? '', 40, y, chartW, Math.min(chartH, 280))) {
                for (const key of ['valuable','rare','inimitable','organised']) {
                    const entry = fw.vrio?.[key];
                    if (!entry) continue;
                    y = scoreBar(doc, key.charAt(0).toUpperCase() + key.slice(1), entry.score ?? 50, undefined, y);
                    if (entry.evidence) {
                        doc.fontSize(7).fillColor(GRAY).font('Helvetica').text(sanitizeText(entry.evidence), 50, y, { width: chartW - 10 });
                        y = doc.y + 4;
                    }
                }
            } else { y += Math.min(chartH, 280) + 8; }
            if (fw.vrio?.verdict) {
                doc.rect(40, y, chartW, 22).fill('#EFF6FF');
                doc.fontSize(9).fillColor(BLUE).font('Helvetica-Bold').text(`Verdict: ${sanitizeText(fw.vrio.verdict)}`, 48, y + 6);
                y += 30;
            }
            drawFooter(doc, page++);
        }

        // Blue Ocean — Strategy Canvas
        if (fw.blue_ocean) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'Blue Ocean Strategy Canvas', y);
            if (!embedChart(doc, charts.blue_ocean_canvas ?? '', 40, y, chartW, chartH)) {
                chartFallbackText(doc, 'Strategy canvas chart unavailable.', 40, y, chartW);
                y += 36;
            } else { y += chartH + 12; }

            // ERRC Grid on same or next page
            if (y > pageBottom - 240) { drawFooter(doc, page++); y = addPage(doc, orgName); }
            y = sectionTitle(doc, 'Blue Ocean ERRC Grid', y);
            if (!embedChart(doc, charts.blue_ocean_errc ?? '', 40, y, chartW, 240)) {
                const errc = fw.blue_ocean?.errc_grid ?? {};
                for (const [action, items] of Object.entries(errc) as [string, any][]) {
                    doc.fontSize(8).fillColor(NAVY).font('Helvetica-Bold').text(action.toUpperCase(), 40, y); y += 14;
                    for (const item of (Array.isArray(items) ? items : [])) {
                        doc.fontSize(7.5).fillColor(GRAY).font('Helvetica').text(`• ${sanitizeText(String(item))}`, 50, y); y = doc.y + 2;
                    }
                    y += 4;
                }
            } else { y += 248; }
            drawFooter(doc, page++);
        }

        // Wardley Map
        if (fw.wardley) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'Wardley Strategic Map', y);
            if (!embedChart(doc, charts.wardley ?? '', 40, y, chartW, chartH)) {
                chartFallbackText(doc, 'Wardley map chart unavailable — see components below.', 40, y, chartW);
                y += 36;
                const components = fw.wardley?.components ?? [];
                for (const c of components.slice(0, 10)) {
                    doc.fontSize(7.5).fillColor(NAVY).font('Helvetica')
                        .text(`${c.name ?? ''} — Evolution: ${c.evolution ?? '?'}, Position: ${c.value_chain_position ?? '?'}`, 40, y, { width: chartW });
                    y = doc.y + 3;
                }
            } else { y += chartH + 8; }
            const warnings = fw.wardley?.strategic_warnings ?? [];
            if (warnings.length > 0) {
                doc.fontSize(7.5).fillColor(ORANGE).font('Helvetica-Oblique')
                    .text(`Strategic warnings: ${warnings.slice(0,2).map((w: string) => sanitizeText(w)).join(' | ')}`, 40, y, { width: chartW });
                y = doc.y + 8;
            }
            drawFooter(doc, page++);
        }

        // Monte Carlo
        if (fw.monte_carlo) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'Monte Carlo LTV:CAC Simulation', y);
            if (!embedChart(doc, charts.monte_carlo ?? '', 40, y, chartW, chartH)) {
                chartFallbackText(doc, 'Monte Carlo histogram unavailable — see percentiles below.', 40, y, chartW);
                y += 36;
                const dists = fw.monte_carlo?.distributions ?? [];
                if (dists.length > 0) {
                    const vals = dists.map((d: any) => typeof d === 'number' ? d : d?.value ?? 0).filter(Number.isFinite);
                    if (vals.length) {
                        const sorted = [...vals].sort((a, b) => a - b);
                        const p10 = sorted[Math.floor(sorted.length * 0.1)];
                        const p50 = sorted[Math.floor(sorted.length * 0.5)];
                        const p90 = sorted[Math.floor(sorted.length * 0.9)];
                        doc.fontSize(8).fillColor(NAVY).font('Helvetica')
                            .text(`P10: ${p10?.toFixed(2)}x  |  P50: ${p50?.toFixed(2)}x  |  P90: ${p90?.toFixed(2)}x`, 40, y);
                        y = doc.y + 10;
                    }
                }
            } else { y += chartH + 8; }
            const drivers = fw.monte_carlo?.risk_drivers ?? [];
            if (drivers.length > 0) {
                doc.fontSize(8).fillColor(NAVY).font('Helvetica-Bold').text('Top Risk Drivers:', 40, y); y += 14;
                for (const d of drivers.slice(0, 4)) {
                    doc.fontSize(7.5).fillColor(GRAY).font('Helvetica')
                        .text(`• ${sanitizeText(d.factor ?? '')}: ${((d.variance_contribution ?? 0) * 100).toFixed(0)}% of variance`, 48, y, { width: chartW });
                    y = doc.y + 3;
                }
            }
            drawFooter(doc, page++);
        }

        // PESTLE
        if (fw.pestle) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'PESTLE Environmental Scan', y);
            if (!embedChart(doc, charts.pestle ?? '', 40, y, chartW, chartH)) {
                chartFallbackText(doc, 'PESTLE chart unavailable — see factors below.', 40, y, chartW);
                y += 36;
                for (const dim of ['political','economic','social','technological','legal','environmental']) {
                    const factors = fw.pestle?.[dim];
                    if (!factors) continue;
                    const list = Array.isArray(factors) ? factors : [factors];
                    for (const f of list.slice(0, 2)) {
                        doc.fontSize(7.5).fillColor(NAVY).font('Helvetica')
                            .text(`${dim.charAt(0).toUpperCase()}: ${sanitizeText(f.factor ?? String(f))}`, 40, y, { width: chartW });
                        y = doc.y + 3;
                    }
                }
            } else { y += chartH + 8; }
            if (fw.pestle?.dominant_force) {
                doc.fontSize(7.5).fillColor(ORANGE).font('Helvetica-Oblique')
                    .text(`Dominant Force: ${sanitizeText(fw.pestle.dominant_force)}`, 40, y, { width: chartW });
                y = doc.y + 8;
            }
            drawFooter(doc, page++);
        }

        // Unit Economics
        if (fw.unit_economics) {
            y = addPage(doc, orgName);
            y = sectionTitle(doc, 'Unit Economics Dashboard', y);
            if (!embedChart(doc, charts.unit_economics ?? '', 40, y, chartW, chartH)) {
                const ue = fw.unit_economics;
                const metrics: [string, string | number | undefined][] = [
                    ['LTV:CAC Ratio', ue?.ltv_cac_ratio ? `${Number(ue.ltv_cac_ratio).toFixed(2)}x` : undefined],
                    ['CAC', ue?.cac ? `$${ue.cac}` : undefined],
                    ['LTV', ue?.ltv ? `$${ue.ltv}` : undefined],
                    ['ARPU', ue?.arpu ? `$${ue.arpu}` : undefined],
                    ['Gross Margin', ue?.gross_margin ? `${ue.gross_margin}%` : undefined],
                    ['Monthly Churn', ue?.churn_rate ? `${ue.churn_rate}%` : undefined],
                    ['CAC Payback', ue?.payback_period ? `${ue.payback_period} mo` : undefined],
                    ['NRR', ue?.nrr ? `${ue.nrr}%` : undefined],
                ];
                for (const [label, val] of metrics) {
                    if (!val) continue;
                    doc.fontSize(8).fillColor(NAVY).font('Helvetica')
                        .text(`${label}: `, 40, y, { continued: true })
                        .font('Helvetica-Bold').text(String(val));
                    y = doc.y + 3;
                }
            } else { y += chartH + 8; }
            const levers = fw.unit_economics?.improvement_levers ?? [];
            if (levers.length) {
                doc.fontSize(8).fillColor(NAVY).font('Helvetica-Bold').text('Improvement Levers:', 40, y); y += 14;
                for (const lever of levers.slice(0, 4)) {
                    doc.fontSize(7.5).fillColor(GRAY).font('Helvetica')
                        .text(`• ${sanitizeText(String(lever))}`, 48, y, { width: chartW - 8 });
                    y = doc.y + 3;
                }
            }
            drawFooter(doc, page++);
        }
    }

    // ── SOURCES APPENDIX ───────────────────────────────────────────────────────
    if (memory.groundedContext) {
        y = addPage(doc, orgName);
        y = sectionTitle(doc, 'Sources Appendix', y);
        doc.fontSize(8).fillColor(GRAY).font('Helvetica')
            .text('The following context and artifacts were discovered and synthesized during the intelligence sweep:', 40, y);
        y += 20;

        const contextLines = memory.groundedContext.split('\n');
        for (const line of contextLines) {
            if (y > pageBottom - 20) { drawFooter(doc, page++); y = addPage(doc, orgName); }
            const trimmed = sanitizeText(line.trim());
            if (!trimmed) { y += 5; continue; }
            doc.fontSize(7).fillColor(NAVY).text(trimmed, 40, y, { width: doc.page.width - 80 });
            y = doc.y + 2;
        }
        drawFooter(doc, page++);
    }

    doc.end();
}
