import PDFDocument from 'pdfkit';
import type { AuditMemory } from './memory.js';

// ─── Design Tokens ────────────────────────────────────────────────────────────
const NAVY   = '#0D1B2A';
const BLUE   = '#1B4F8A';
const ACCENT = '#2563EB';
const GRAY   = '#6B7280';
const WHITE  = '#FFFFFF';
const RED    = '#DC2626';
const GREEN  = '#16A34A';
const FOOTER = 'Generated by VelocityCSO.com — Powered by Gemini Flash';

function drawHeader(doc: PDFKit.PDFDocument, title: string) {
    doc.rect(0, 0, doc.page.width, 56).fill(NAVY);
    doc.fontSize(8).fillColor(WHITE).font('Helvetica')
        .text('CONFIDENTIAL STRATEGY AUDIT', 40, 20, { align: 'left' });
    doc.fontSize(8).fillColor(WHITE)
        .text(title, 0, 20, { align: 'right', width: doc.page.width - 40 });
    doc.fillColor(NAVY);
}

function drawFooter(doc: PDFKit.PDFDocument, page: number) {
    const y = doc.page.height - 36;
    doc.rect(0, y, doc.page.width, 36).fill(NAVY);
    doc.fontSize(7).fillColor(WHITE).font('Helvetica')
        .text(FOOTER, 40, y + 12, { align: 'left' });
    doc.text(`Page ${page}`, 0, y + 12, { align: 'right', width: doc.page.width - 40 });
}

function sectionTitle(doc: PDFKit.PDFDocument, text: string, y: number) {
    doc.rect(40, y, 4, 18).fill(ACCENT);
    doc.fontSize(11).fillColor(NAVY).font('Helvetica-Bold')
        .text(text, 52, y + 2);
    return y + 28;
}

function scoreBar(doc: PDFKit.PDFDocument, label: string, score: number, y: number) {
    const barW = 200;
    const filled = Math.round((score / 100) * barW);
    const color = score >= 70 ? GREEN : score >= 40 ? BLUE : RED;
    doc.fontSize(8).fillColor(NAVY).font('Helvetica').text(label, 40, y, { width: 160 });
    doc.rect(210, y + 1, barW, 8).fill('#E5E7EB');
    doc.rect(210, y + 1, filled, 8).fill(color);
    doc.fontSize(8).fillColor(NAVY).text(`${score}`, 418, y);
    return y + 16;
}

// ─── Extract org name from business context ───────────────────────────────────
function extractOrgName(context: string): string {
    const match = context.match(/^([A-Z][a-zA-Z\s&]{2,40})/);
    return match ? match[1].trim() : 'Your Organisation';
}

// ─── Extract killer move (first bold/headline sentence from report) ───────────
function extractKillerMove(report: string): string {
    const match = report.match(/\*\*([^*]{10,120})\*\*/);
    if (match) return match[1].trim().slice(0, 120);
    const lines = report.split('\n').filter(l => l.trim().length > 20);
    return lines[0]?.replace(/[#*]/g, '').trim().slice(0, 120) || 'Strategic audit complete.';
}

// ─── Main export ──────────────────────────────────────────────────────────────
export function generatePDF(memory: AuditMemory): Buffer {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ size: 'A4', margin: 0, bufferPages: true });
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const orgName = extractOrgName(memory.businessContext);
    const killerMove = extractKillerMove(memory.report);
    const overallScore = Object.values(memory.dimensionScores).length
        ? Math.round(Object.values(memory.dimensionScores).reduce((a, b) => a + b, 0) / Object.values(memory.dimensionScores).length)
        : 0;
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

    // ── PAGE 1: Cover + Executive Verdict ─────────────────────────────────────
    drawHeader(doc, orgName);

    // Cover block
    doc.rect(0, 56, doc.page.width, 180).fill(NAVY);
    doc.fontSize(22).fillColor(WHITE).font('Helvetica-Bold')
        .text('Executive Strategy Audit', 40, 80);
    doc.fontSize(16).fillColor('#93C5FD').font('Helvetica')
        .text(orgName, 40, 112);
    doc.fontSize(9).fillColor(GRAY)
        .text(`${date}  ·  Confidence Score: ${overallScore}/100`, 40, 140);

    // Killer Move
    let y = 260;
    y = sectionTitle(doc, 'Executive Verdict', y);
    doc.fontSize(18).fillColor(NAVY).font('Helvetica-Bold')
        .text(`"${killerMove}"`, 40, y, { width: doc.page.width - 80 });
    y = doc.y + 24;

    // Moat strength badge
    const moatLabel = overallScore >= 70 ? 'STRONG MOAT' : overallScore >= 40 ? 'DEVELOPING MOAT' : 'FRAGILE MOAT';
    const moatColor = overallScore >= 70 ? GREEN : overallScore >= 40 ? BLUE : RED;
    doc.rect(40, y, 140, 28).fill(moatColor);
    doc.fontSize(11).fillColor(WHITE).font('Helvetica-Bold')
        .text(moatLabel, 40, y + 8, { width: 140, align: 'center' });
    doc.fontSize(10).fillColor(NAVY).font('Helvetica')
        .text(`Overall Score: ${overallScore}/100`, 200, y + 8);

    drawFooter(doc, 1);

    // ── PAGE 2: 15-Dimension Heatmap ──────────────────────────────────────────
    doc.addPage();
    drawHeader(doc, orgName);
    y = 72;
    y = sectionTitle(doc, '15-Dimension Strategic Heatmap', y);

    const dims = memory.dimensionScores;
    const categories: Record<string, string[]> = {
        'Market':     ['TAM Viability', 'Target Precision', 'Trend Adoption'],
        'Strategy':   ['Competitive Defensibility', 'Model Innovation', 'Flywheel Potential'],
        'Commercial': ['Pricing Power', 'CAC/LTV Ratio', 'Market Entry Speed'],
        'Operations': ['Execution Speed', 'Scalability', 'ESG Posture'],
        'Finance':    ['ROI Projection', 'Risk Tolerance', 'Capital Efficiency'],
    };

    for (const [cat, dimList] of Object.entries(categories)) {
        doc.fontSize(9).fillColor(ACCENT).font('Helvetica-Bold').text(cat.toUpperCase(), 40, y);
        y += 14;
        for (const dim of dimList) {
            y = scoreBar(doc, dim, dims[dim] ?? 0, y);
        }
        y += 8;
    }

    // Legend
    y += 8;
    doc.fontSize(8).fillColor(GRAY).font('Helvetica')
        .text('■ Strong (70-100)', 40, y, { continued: true }).fillColor(GREEN)
        .text('  ■ Developing (40-69)', { continued: true }).fillColor(BLUE)
        .text('  ■ At Risk (0-39)').fillColor(RED);

    drawFooter(doc, 2);

    // ── PAGES 3-5: Strategic Asymmetries (two-column) ─────────────────────────
    const reportSections = memory.report.split(/\n#{2,3} /);

    let page = 3;
    let colPage = false;
    for (let i = 1; i < Math.min(reportSections.length, 7); i++) {
        if (!colPage) {
            doc.addPage();
            drawHeader(doc, orgName);
            y = 72;
            y = sectionTitle(doc, 'Strategic Asymmetries — Deep Dive', y);
            colPage = true;
        }

        const section = reportSections[i];
        const lines = section.split('\n');
        const heading = lines[0].replace(/[#*]/g, '').trim();
        const body = lines.slice(1).join('\n').replace(/[*#]/g, '').trim().slice(0, 600);

        // Two-column: left = reality, right = asymmetric play
        const midX = doc.page.width / 2;
        const colW = midX - 60;

        doc.rect(40, y, colW, 14).fill('#F3F4F6');
        doc.fontSize(8).fillColor(ACCENT).font('Helvetica-Bold')
            .text('COMPETITIVE REALITY', 44, y + 3);
        doc.rect(midX + 20, y, colW, 14).fill('#EFF6FF');
        doc.fontSize(8).fillColor(GREEN).font('Helvetica-Bold')
            .text('ASYMMETRIC PLAY', midX + 24, y + 3);

        y += 18;
        doc.fontSize(9).fillColor(NAVY).font('Helvetica-Bold')
            .text(heading, 40, y, { width: colW });
        const afterHeading = doc.y + 4;

        doc.fontSize(8).fillColor(NAVY).font('Helvetica')
            .text(body.slice(0, 300), 40, afterHeading, { width: colW });
        const leftBottom = doc.y;

        doc.fontSize(8).fillColor(NAVY).font('Helvetica')
            .text(body.slice(300) || '—', midX + 20, afterHeading, { width: colW });
        const rightBottom = doc.y;

        y = Math.max(leftBottom, rightBottom) + 20;

        if (y > doc.page.height - 80) {
            drawFooter(doc, page++);
            doc.addPage();
            drawHeader(doc, orgName);
            y = 72;
            colPage = false;
        }
    }
    if (colPage) drawFooter(doc, page++);

    // ── Final Page: Risk & Stress Test Summary ────────────────────────────────
    doc.addPage();
    drawHeader(doc, orgName);
    y = 72;
    y = sectionTitle(doc, 'Risk & Stress Test Summary', y);

    const scenarios = ['RECESSION', 'PRICE_WAR', 'SCALE_UP', 'TALENT'];
    const scenarioLabels: Record<string, string> = {
        RECESSION: 'Economic Recession',
        PRICE_WAR: 'Competitor Price War',
        SCALE_UP: 'Aggressive Scale-Up',
        TALENT: 'Global Talent Shortage',
    };

    // Table header
    doc.rect(40, y, doc.page.width - 80, 18).fill(NAVY);
    doc.fontSize(8).fillColor(WHITE).font('Helvetica-Bold')
        .text('Scenario', 44, y + 5, { width: 160 })
        .text('Baseline Score', 210, y + 5, { width: 100 })
        .text('Risk Level', 320, y + 5, { width: 100 })
        .text('Verdict', 430, y + 5);
    y += 18;

    for (const s of scenarios) {
        const bg = scenarios.indexOf(s) % 2 === 0 ? '#F9FAFB' : WHITE;
        doc.rect(40, y, doc.page.width - 80, 18).fill(bg);
        const risk = overallScore >= 70 ? 'LOW' : overallScore >= 40 ? 'MEDIUM' : 'HIGH';
        const riskColor = risk === 'LOW' ? GREEN : risk === 'MEDIUM' ? BLUE : RED;
        doc.fontSize(8).fillColor(NAVY).font('Helvetica')
            .text(scenarioLabels[s], 44, y + 5, { width: 160 })
            .text(`${overallScore}/100`, 210, y + 5, { width: 100 });
        doc.fillColor(riskColor).text(risk, 320, y + 5, { width: 100 });
        doc.fillColor(NAVY).text(risk === 'LOW' ? 'Resilient' : risk === 'MEDIUM' ? 'Monitor' : 'Vulnerable', 430, y + 5);
        y += 18;
    }

    y += 20;
    doc.fontSize(8).fillColor(GRAY).font('Helvetica')
        .text('Run a live Stress Test from the VelocityCSO dashboard for real-time scenario recalculation.', 40, y, { width: doc.page.width - 80 });

    drawFooter(doc, page);

    doc.end();
    return Buffer.concat(chunks);
}
